### ISSUE TITLE
Cant get interaction to work

### ISSUE THREAD

**Issue by yanniboi** [Playwo/Discord.InteractivityAddon#21]
Hi, I've set up some of the example commands on my bot, and it looks like everything is working, except the interaction.

For example. `!confirm` It shows the reactions on the bot posted message, however no matter how often I react to the post, it always times out.

Could you offer some advice on how to debug this? There are no errors that I can find.

**Comment by Playwo** [comment]
Are you getting warnings about the gateway task being blocked?

**Comment by yanniboi** [comment]
My issue was that I wasn't running my commands asynchronously.

Changing:

` [Command("confirm")]`

to:

` [Command("confirm", RunMode = RunMode.Async)]`

fixed my issue.
