### ISSUE TITLE
Can't create child classes as suggested when using the assembly as a dependency

### ISSUE THREAD

**Issue by SKukreja** [Playwo/Discord.InteractivityAddon#28]
![image](https://user-images.githubusercontent.com/15660268/132455557-3074289f-0fe7-48e4-9b1a-ff601d9bcb83.png)

The paginator class has its constructor set as internal, meaning child classes cannot reference it from another solution, even when using the supplied builder patterns. If I'm not mistaken this makes it impossible to inherit from the class without getting errors when adding the assembly as a dependency.

![image](https://user-images.githubusercontent.com/15660268/132455834-850013e8-96b9-44f6-9c45-1aff87eb687e.png)

**Comment by Playwo** [comment]
That was a little oversight, thanks for letting me know :)
I have made it public now.
