### ISSUE TITLE
[Suggestion] Remove reactions on Confirmation Message after Timeout/Cancel

### ISSUE THREAD

**Issue by EBro912** [Playwo/Discord.InteractivityAddon#5]
I've been fiddling around with this library for a bit, testing out the Confirmation feature, and I noticed that if you don't delete the confirmation message after the user reacts that the two reactions stick around after the message is edited via Timeout or Cancellation. It would be nice to have an option in the ConfirmationBuilder to remove these reactions after either one of these actions, and I didn't want to make a whole separate pull request just for a feature as simple as this. 

Loving the library so far by the way, keep up the good work!

**Comment by Playwo** [comment]
It is possible to make it delete the confirmation message using the DeletionOption AfterCapturedContext. 
I could make it so that the remaining reactions are deleted if you add the Valid/Invalid DeletionOption.
Let's say Valid just removes the reaction added by the bot (and the user who is meant to click it) and invalid removes every reaction except the one by the bot and the correct user.

**Comment by EBro912** [comment]
That sounds perfect. It would also be nice if all the reactions were removed (including the bot’s and correct user) after a route has been chosen.
Ex: Confirmation message is sent -> user reacts with the “decline” option -> Message is edited to the Decline Embed -> All reactions are removed from the message 

I think that would make things look a lot cleaner, on top of what you suggested.

**Comment by Playwo** [comment]
I've decided to make the DeletionOption valid do just that. It had no purpose for Confirmations anyway. Specifying Valid will just delete all reactions after the Confirmatin "exits". Invalids has a purpose so that one will not affect the reaction deletion.

**Comment by EBro912** [comment]
Awesome, sounds good. Can’t wait!

**Comment by Playwo** [comment]
It should be on Nuget very soon. The action has pushed it, it's just nuget processing now.
