### ISSUE TITLE
SendConfirmationAsync null reference exception

### ISSUE THREAD

**Issue by stageosu** [Playwo/Discord.InteractivityAddon#7]
When executing the following code, a null reference exception is encountered.

```cs
var builder = new ConfirmationBuilder()
.WithContent("test")
.Build();

await _interactivityService.SendConfirmationAsync(builder, Context.Channel);
```

However, when instead writing `.WithContent("test", new EmbedBuilder())`, the code runs without errors.

The `EmbedBuilder` is listed as an optional parameter to the `.WithContent()` method. This may need to be changed.

**Comment by Playwo** [comment]
The cleanest solution in my opinion would be to remove the problematic overload. The WithContent overload that takes a page already covers the functionality and it's not much harder to make a page than to enter it like that.
